import { MenuCategory, MenuSubcategory } from "@/types";

export const sampleCategories: MenuCategory[] = [
  { id: "cases", name: { RU: "Чехлы", KZ: "Қаптар" }, order: 1, icon: "📱" },
  { id: "earphones", name: { RU: "Наушники", KZ: "Құлаққаптар" }, order: 2, icon: "🎧" },
  { id: "chargers", name: { RU: "Зарядки", KZ: "Зарядтағыштар" }, order: 3, icon: "🔌" },
  { id: "cables", name: { RU: "Кабели", KZ: "Кабельдер" }, order: 4, icon: "🔗" },
  { id: "powerbanks", name: { RU: "Повербанки", KZ: "Повербанктер" }, order: 5, icon: "🔋" },
  { id: "screen-protectors", name: { RU: "Защитные стекла", KZ: "Қорғаныш әйнектер" }, order: 6, icon: "🛡️" },
  { id: "holders", name: { RU: "Держатели", KZ: "Ұстағыштар" }, order: 7, icon: "🗄️" },
  { id: "speakers", name: { RU: "Колонки", KZ: "Динамиктер" }, order: 8, icon: "🔊" },
];

const sameName = (name: string) => ({ RU: name, KZ: name });

export const sampleSubcategories: MenuSubcategory[] = [
  { id: "cases-iphone", name: sameName("Iphone"), categoryId: "cases", order: 1 },
  { id: "cases-samsung", name: sameName("Samsung"), categoryId: "cases", order: 2 },
  { id: "cases-redmi", name: sameName("Redmi"), categoryId: "cases", order: 3 },
  { id: "cases-google-pixel", name: sameName("Google Pixel"), categoryId: "cases", order: 4 },
  { id: "cases-iphone16", name: sameName("Iphone 16"), categoryId: "cases", parentId: "cases-iphone", order: 1 },
  { id: "cases-iphone16-pro", name: sameName("Iphone 16 Pro"), categoryId: "cases", parentId: "cases-iphone", order: 2 },
  { id: "cases-iphone16-pro-max", name: sameName("Iphone 16 Pro Max"), categoryId: "cases", parentId: "cases-iphone", order: 3 },
  { id: "cases-iphone17", name: sameName("Iphone 17"), categoryId: "cases", parentId: "cases-iphone", order: 4 },
  { id: "cases-iphone17-pro", name: sameName("Iphone 17 Pro"), categoryId: "cases", parentId: "cases-iphone", order: 5 },
  { id: "cases-iphone17-pro-max", name: sameName("Iphone 17 Pro Max"), categoryId: "cases", parentId: "cases-iphone", order: 6 },
  { id: "cases-iphone15", name: sameName("Iphone 15"), categoryId: "cases", parentId: "cases-iphone", order: 7 },
  { id: "cases-samsung-s25", name: sameName("Samsung S25"), categoryId: "cases", parentId: "cases-samsung", order: 1 },
  { id: "cases-samsung-s25-ultra", name: sameName("Samsung S25 Ultra"), categoryId: "cases", parentId: "cases-samsung", order: 2 },
  { id: "cases-samsung-s24", name: sameName("Samsung S24"), categoryId: "cases", parentId: "cases-samsung", order: 3 },
  { id: "cases-samsung-s24-ultra", name: sameName("Samsung S24 Ultra"), categoryId: "cases", parentId: "cases-samsung", order: 4 },
  { id: "cases-samsung-a56", name: sameName("Samsung A56"), categoryId: "cases", parentId: "cases-samsung", order: 5 },
  { id: "cases-samsung-a36", name: sameName("Samsung A36"), categoryId: "cases", parentId: "cases-samsung", order: 6 },
  { id: "cases-redmi-note-14", name: sameName("Redmi Note 14"), categoryId: "cases", parentId: "cases-redmi", order: 1 },
  { id: "cases-redmi-note-14-pro", name: sameName("Redmi Note 14 Pro"), categoryId: "cases", parentId: "cases-redmi", order: 2 },
  { id: "cases-redmi-note-13", name: sameName("Redmi Note 13"), categoryId: "cases", parentId: "cases-redmi", order: 3 },
  { id: "cases-redmi-14c", name: sameName("Redmi 14C"), categoryId: "cases", parentId: "cases-redmi", order: 4 },
  { id: "cases-redmi-13c", name: sameName("Redmi 13C"), categoryId: "cases", parentId: "cases-redmi", order: 5 },
  { id: "cases-google-pixel-9", name: sameName("Google Pixel 9"), categoryId: "cases", parentId: "cases-google-pixel", order: 1 },
  { id: "cases-google-pixel-9-pro", name: sameName("Google Pixel 9 Pro"), categoryId: "cases", parentId: "cases-google-pixel", order: 2 },
  { id: "cases-google-pixel-9-pro-xl", name: sameName("Google Pixel 9 Pro XL"), categoryId: "cases", parentId: "cases-google-pixel", order: 3 },
  { id: "cases-google-pixel-8", name: sameName("Google Pixel 8"), categoryId: "cases", parentId: "cases-google-pixel", order: 4 },
  { id: "cases-google-pixel-8-pro", name: sameName("Google Pixel 8 Pro"), categoryId: "cases", parentId: "cases-google-pixel", order: 5 },
  { id: "chargers-typec", name: sameName("Type-C"), categoryId: "chargers", order: 1 },
  { id: "chargers-lightning", name: sameName("Lightning"), categoryId: "chargers", order: 2 },
  { id: "chargers-wireless", name: { RU: "Беспроводные", KZ: "Сымсыз" }, categoryId: "chargers", order: 3 },
  { id: "chargers-laptop", name: { RU: "Для ноутбуков", KZ: "Ноутбуктарға" }, categoryId: "chargers", order: 4 },
  { id: "chargers-car", name: { RU: "Автомобильные", KZ: "Автокөлік" }, categoryId: "chargers", order: 5 },
  { id: "ear-airpods", name: sameName("AirPods"), categoryId: "earphones", order: 1 },
  { id: "ear-earpods", name: { RU: "EarPods (проводные)", KZ: "EarPods (сымды)" }, categoryId: "earphones", order: 2 },
  { id: "ear-samsung", name: sameName("Samsung Buds"), categoryId: "earphones", order: 3 },
  { id: "ear-budget", name: { RU: "Бюджетные TWS", KZ: "Бюджетті TWS" }, categoryId: "earphones", order: 4 },
  { id: "cables-typec", name: sameName("Type-C"), categoryId: "cables", order: 1 },
  { id: "cables-lightning", name: sameName("Lightning"), categoryId: "cables", order: 2 },
  { id: "cables-micro", name: sameName("Micro USB"), categoryId: "cables", order: 3 },
  { id: "sp-iphone", name: { RU: "Для iPhone", KZ: "iPhone үшін" }, categoryId: "screen-protectors", order: 1 },
  { id: "sp-samsung", name: { RU: "Для Samsung", KZ: "Samsung үшін" }, categoryId: "screen-protectors", order: 2 },
];
